### ISSUE TITLE
VSCode 里面已经不能搜索到该插件

### ISSUE THREAD

**Issue by Reasuon** [summerscar/vscode-live2d#1]
VSCode程序内自带的搜索插件已经不能搜索到该插件，而官方页面上虽然能搜索到该插件，但是显示没有上市场，请问我现在还能通过VSCode下载到该插件吗？能的话方便给个操作的参考吗？谢谢

![image](https://user-images.githubusercontent.com/38161433/73710738-cc0ae800-473f-11ea-9053-81d6b23cb070.png)

**Comment by summerscar** [comment]
官方给我发了封请求授权的邮件 
so 干脆下架了   只能通过开发模式加载了
